name: Generate Snake

on:
  schedule:
    - cron: "0 3 * * *"   # roda todo dia às 03:00 UTC
  workflow_dispatch:       # permite rodar manualmente
  push:
    branches: ["main"]     # opcional: gera quando você fizer push na main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: omatheuscardoso
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish to GitHub Pages (branch output)
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
